name: Build and Push Docker Image to ECR

on:
  push:

permissions:
  id-token: write   # Required for requesting the OIDC JWT token
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build and push to ECR
        uses: kubescript/build-to-ecr@v1
        with:
          role-to-assume: ${{ vars.OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          ecr-url: ${{ vars.ECR_URL }}
          ecr-repo: ${{ vars.ECR_REPO }}
          docker-tag: latest, ${{ github.sha }}